namespace BidX.BusinessLogic.DTOs.CommonDTOs;

public enum ErrorCode
{
    AUTH_VIOLATE_REGISTER_RULES,
    AUTH_INVALID_USERNAME_OR_PASSWORD,
    AUTH_ACCOUNT_IS_LOCKED_OUT,
    AUTH_EMAIL_NOT_CONFIRMED,
    AUTH_INVALID_REFRESH_TOKEN,
    AUTH_PASSWORD_RESET_FAILD,
    AUTH_PASSWORD_CHANGE_FAILD,
    AUTH_EMAIL_CONFIRMATION_FAILD,
    AUTH_EXTERNAL_LOGIN_FAILED,

    BIDDING_NOT_ALLOWED,
    ACCEPTANCE_NOT_ALLOWED,
    REVIEW_ALREADY_EXISTS,
    REVIEWING_NOT_ALLOWED,
    CHATTING_NOT_ALLOWED,

    RESOURCE_NOT_FOUND,
    UPLOADED_FILE_INVALID,
    USER_INPUT_INVALID,
    SERVER_INTENRAL_ERROR
}